### ISSUE TITLE
createStateMachine should supply a default dummy role arn if one is not provided 

### ISSUE THREAD

**Issue by PressX2Jason** [mwkim0919/stepfunctions-local-dashboard#4]
The filed currently is auto populated with a same arn. I suggest we use that arn if nothing is provided at the time of submit

**Comment by mwkim0919** [comment]
Related commit: https://github.com/mwkim0919/stepfunctions-local-dashboard/commit/ec9a86e7c6c662e05f4bc2c7b7fae19ef4d09c4d

Closing this.
